### ISSUE TITLE
Why not revoce erridx whe panic occured?

### ISSUE THREAD

**Issue by RaynorGu** [aarzilli/golua#96] opened 2021-02-02 04:29 UTC
![image](https://user-images.githubusercontent.com/7893714/106551742-dcbb8d00-6550-11eb-9f3a-176636143b8e.png)

L.Remove(err_idx) not executed when panic occurred, it will stay in the stack, make stack grow

**Comment by RaynorGu** [comment] 2021-02-02 04:32
![image](https://user-images.githubusercontent.com/7893714/106552502-70da2400-6552-11eb-89b2-b5cc059936c6.png)
This is an example, make stack top bigger

**Comment by aarzilli** [comment] 2021-02-02 07:34
It doesn't matter, anything that was pushed on the stack between pcall and the point where the exception happens will be leaked forever. Duplicate of #24

**Closed by aarzilli** 2021-02-02 07:34 UTC
